version: '2'
services:
  influxdb:
    image: "influxdb:1.7.9"
    ports:
     - 8086:8086
     - 8083:8083
    volumes: 
      - ./influxdb:/var/lib/influxdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - INFLUXDB_DB=home_assistant
    network_mode: host
    container_name: influxdb

  rabbitmq:
    image: "rabbitmq:3.7.23-management"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5672:5672
      - 15672:15672
    network_mode: host
    container_name: rabbit

  mosquitto:
    image: "eclipse-mosquitto:1.6.8"
    ports:
      - 1883:1883
      - 9001:9001
    volumes: 
      - ./mosquitto:/mosquitto
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    container_name: mosquitto

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbitmq
      - influxdb
      - mosquitto
    network_mode: host
    command: localhost:1883 localhost:8086 localhost:5672