version: "2"
services:
  ha:
    image: homeassistant/home-assistant:2022.11
    # ports:
    # - 8123:8123
    volumes:
      - ./homeassistant:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mysql
    network_mode: host
    container_name: ha
    restart: unless-stopped

  nginx:
    image: nginx:1.23.2
    # ports:
    # - 8123:8123
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/arekha.duckdns.org/fullchain.pem:/etc/letsencrypt/live/arekha.duckdns.org/fullchain.pem:ro
      - /etc/letsencrypt/live/arekha.duckdns.org/privkey.pem:/etc/letsencrypt/live/arekha.duckdns.org/privkey.pem:ro
      - ./nginx/dhparams.pem:/etc/nginx/ssl/dhparams.pem:ro
    depends_on:
      - ha
    network_mode: host
    container_name: nginx
    restart: unless-stopped

  grafana:
    image: "grafana/grafana:9.2.1"
    # ports:
    # - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    container_name: grafana
    network_mode: host
    user: "1000"
    restart: unless-stopped

  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    # ports:
    # - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: wsadqe
    container_name: mysql
    network_mode: host
    restart: unless-stopped

  backup-creator:
    build:
      context: ./services/Services.BackupCreator
      dockerfile: Dockerfile
    environment:
      - WRAPPER_ENVIRONMENT=Docker
      - HOST=Win
    volumes:
      - ./:/maindir
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    container_name: bc
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    depends_on:
      - ha
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    #    ports:
    # Frontend port
    #      - 8080:8080
    environment:
      - TZ=Europe/Warsaw
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2660192-if00:/dev/ttyACM0
    network_mode: host
    container_name: z2m
    restart: unless-stopped

  node-red:
    image: nodered/node-red:2.2.3
    environment:
      - TZ=Europe/Warsaw
    #    ports:
    #      - "1880:1880"
    volumes:
      - ./nodered:/data
    network_mode: host
    container_name: node-red

  # backup-creator2:
  #   build:
  #     context: ./services/PythonServices/BackupCreator
  #     dockerfile: Dockerfile
  #   ports:
  #    - 5001:5001
  #   environment:
  #     - WRAPPER_ENVIRONMENT=Docker
  #   volumes:
  #     - ./:/maindir
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   network_mode: host
  #   container_name: bc2
