version: "2"
services:
  logstash:
    image: logstash:8.6.2
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./homeassistant:/usr/share/homeassistant
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    container_name: logstash
    network_mode: host
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.6.2
    # ports:
    # - 9200:9200
    # - 9300:9300
    environment:
      - cluster.name=es-prod-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    network_mode: host
    container_name: elasticsearch
    restart: unless-stopped

  kibana:
    image: kibana:8.6.2
    # ports:
    # - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/opt/kibana/config/kibana.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    container_name: kibana
    network_mode: host
    depends_on:
      - elasticsearch
    restart: unless-stopped
