version: '2'
services:
  ha:  
    image: "homeassistant/home-assistant:0.96.5"
    ports:
     - 8123:8123
    volumes: 
      - ./homeassistant:/config
    network_mode: host
    container_name: ha
    
  grafana:
    image: "grafana/grafana:6.2.5"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    container_name: grafana
    network_mode: host
    user: "1000"

  backup-creator:
    build: 
      context: ./services/Services.BackupCreator
      dockerfile: Dockerfile
    environment: 
      - WRAPPER_ENVIRONMENT=Docker
      - HOST=Win
    volumes:
      - ./:/maindir
    network_mode: host
    container_name: bc
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wsadqe
    container_name: mysql
    network_mode: host
