version: '3'
services:
  ha:
    image: "homeassistant/raspberrypi3-homeassistant:0.82.0"
    ports:
     - 8123:8123
    volumes: 
      - ./homeassistant:/config
    depends_on: 
      - influxdb
  influxdb:
    image: "influxdb:1.7.0"
    ports:
     - 8086:8086
     - 8083:8083
    volumes: 
      - ./influxdb:/var/lib/influxdb
    environment: 
      - INFLUXDB_DB=home_assistant
  grafana:
    image: "fg2it/grafana-armhf:v5.0.4"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on: 
      - influxdb