version: '2'
services:
  ha:
    image: "homeassistant/raspberrypi3-homeassistant:0.91.4"
    ports:
     - 8123:8123
    volumes: 
      - ./homeassistant:/config
      - /etc/letsencrypt:/etc/letsencrypt
    network_mode: host
    container_name: ha

  grafana:
    image: "proxx/grafana-armv7:6.1.1"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    user: "root"
    network_mode: host
    container_name: grafana
    
  data-collector:
    build:
      context: ./services/DataCollector
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment: 
      - WRAPPER_ENVIRONMENT=Docker
    network_mode: host
    container_name: dc

  home-assistant-wrapper:
    build: 
      context: ./services/Services.Wrapper.HomeAssistant
      dockerfile: Dockerfile
    environment: 
      - WRAPPER_ENVIRONMENT=Docker
    network_mode: host
    container_name: haw

  backup-creator:
    build: 
      context: ./services/Services.BackupCreator
      dockerfile: Dockerfile
    environment: 
      - WRAPPER_ENVIRONMENT=Docker
      - HOST=Rpi
    volumes:
      - ./:/maindir
    network_mode: host
    container_name: bc

  automation-runner:
    build: 
      context: ./services/AutomationRunner/AutomationRunner
      dockerfile: Dockerfile
    environment: 
      - WRAPPER_ENVIRONMENT=Docker
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    container_name: ar
  