version: '2'
services:
  ha:  
    image: "homeassistant/home-assistant:0.88.2"
    ports:
     - 8123:8123
    volumes: 
      - ./homeassistant:/config
    container_name: ha
    
  grafana:
    image: "grafana/grafana:6.0.0"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    container_name: grafana
    user: "104"
