version: "2"
services:
  ha:
    image: homeassistant/home-assistant:2021.12
    # ports:
    # - 8123:8123
    volumes:
      - ./homeassistant:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mysql
    network_mode: host
    container_name: ha
    restart: unless-stopped

  grafana:
    image: "grafana/grafana:8.3.2"
    # ports:
    # - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    container_name: grafana
    network_mode: host
    user: "1000"
    restart: unless-stopped

  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    # ports:
    # - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: wsadqe
    container_name: mysql
    network_mode: host
    restart: unless-stopped

  backup-creator:
    build:
      context: ./services/Services.BackupCreator
      dockerfile: Dockerfile
    environment:
      - WRAPPER_ENVIRONMENT=Docker
      - HOST=Win
    volumes:
      - ./:/maindir
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    container_name: bc
    restart: unless-stopped

  # backup-creator2:
  #   build:
  #     context: ./services/PythonServices/BackupCreator
  #     dockerfile: Dockerfile
  #   ports:
  #    - 5001:5001
  #   environment:
  #     - WRAPPER_ENVIRONMENT=Docker
  #   volumes:
  #     - ./:/maindir
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   network_mode: host
  #   container_name: bc2
