version: '2'
services:
  ha:
    image: "homeassistant/raspberrypi3-homeassistant:0.84.6"
    ports:
     - 8123:8123
    volumes: 
      - ./homeassistant:/config
      - /etc/letsencrypt:/etc/letsencrypt
    container_name: ha

  grafana:
    image: "proxx/grafana-armv7:v6.0.0"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    container_name: grafana
    user: "104"

  data-collector:
    build:
      context: ./services/DataCollector
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment: 
      - WRAPPER_ENVIRONMENT=Docker
    container_name: dc

  home-assistant-wrapper:
    build: 
      context: ./services/Services.Wrapper.HomeAssistant
      dockerfile: Dockerfile
    environment: 
      - WRAPPER_ENVIRONMENT=Docker
    container_name: haw

  backup-creator:
    build: 
      context: ./services/Services.BackupCreator
      dockerfile: Dockerfile
    environment: 
      - WRAPPER_ENVIRONMENT=Docker
    volumes:
      - ./:/maindir
    container_name: bc



  