version: '2'
services:
  logstash:  
    image: "ind3x/rpi-logstash"
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    volumes: 
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./homeassistant:/usr/share/homeassistant
    network_mode: host
    container_name: logstash
    depends_on: 
      - elasticsearch

  elasticsearch:
    image: "ind3x/rpi-elasticsearch"
    ports:
     - 9200:9200
     - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    network_mode: host
    container_name: elasticsearch

  kibana:
    image: "ind3x/rpi-kibana"
    ports:
     - 5601:5601
    environment:
      NODE_OPTIONS: '--max-old-space-size=128'
    #volumes:
    #  - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    #  - ./kibana/data:/usr/share/kibana/data
    container_name: kibana
    network_mode: host
    depends_on: 
      - elasticsearch
