version: '2'
services:
  logstash:  
    image: "docker.elastic.co/logstash/logstash:6.6.2"
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    volumes: 
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./homeassistant:/usr/share/homeassistant
    container_name: logstash
    depends_on: 
      - elasticsearch

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.6.2"
    ports:
     - 9200:9200
     - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    container_name: elasticsearch

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.6.2"
    ports:
     - 5601:5601
    #volumes:
    #  - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    #  - ./kibana/data:/usr/share/kibana/data
    container_name: kibana
    depends_on: 
      - elasticsearch