version: '2'
services:
  ha:  
    image: "homeassistant/home-assistant:0.84.6"
    ports:
     - 8123:8123
    volumes: 
      - ./homeassistant:/config
    container_name: ha
    
  grafana:
    image: "grafana/grafana:6.0.0"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    container_name: grafana
    user: "104"

  seq:
    image: "datalust/seq:5.0.2787"
    ports:
      - 5341:80
    volumes:
      - seq:/data
    environment: 
      - ACCEPT_EULA=Y
    container_name: seq

  backup-creator:
    build: 
      context: ./services/Services.BackupCreator
      dockerfile: Dockerfile
    environment: 
      - WRAPPER_ENVIRONMENT=Docker
      - HOST=Win
    volumes:
      - ./:/maindir
    container_name: bc

volumes:
  seq:
