version: '2'
services:
  ha:
    image: "homeassistant/raspberrypi3-homeassistant:0.82.0"
    ports:
     - 8123:8123
    volumes: 
      - ./homeassistant:/config

  grafana:
    image: "fg2it/grafana-armhf:v5.0.4"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana

  # data-collector:
  #   build: ./services/DataCollector/Dockerfile
  #   ports:
  #     - 5000:5000
  #   depends_on: 
  #     - rabbitmq

  home-assistant-wrapper:
    build: 
      context: ./services/Services.Wrapper.HomeAssistant
      dockerfile: Dockerfile



  