version: '2'
services:
  ha:  
    image: "homeassistant/home-assistant:0.91.4"
    ports:
     - 8123:8123
    volumes: 
      - ./homeassistant:/config
    network_mode: host
    container_name: ha
    
  grafana:
    image: "grafana/grafana:6.1.1"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    container_name: grafana
    network_mode: host
    user: "1000"

  backup-creator:
    build: 
      context: ./services/Services.BackupCreator
      dockerfile: Dockerfile
    environment: 
      - WRAPPER_ENVIRONMENT=Docker
      - HOST=Win
    volumes:
      - ./:/maindir
    network_mode: host
    container_name: bc
