- alias: Oczyszczacz powietrza - wyłącz
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: 
      - fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    below: 20
    for:
      minutes: 3
  action:
    - service: fan.turn_off
      entity_id: fan.air_purifier_pro

- alias: Oczyszczacz powietrza - włącz
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 20
    for:
      minutes: 3
  action:
    - service: fan.turn_on
      entity_id: fan.air_purifier_pro

- alias: Oczyszczacz powietrza - auto
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 20
    below: 25
  action:
    - service: fan.set_speed
      entity_id: fan.air_purifier_pro
      data_template:
        speed: auto

- alias: Oczyszczacz powietrza - favorite
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 25
  action:
    - service: fan.set_speed
      entity_id: fan.air_purifier_pro
      data_template:
        speed: favorite

- alias: Oczyszczacz powietrza - poziom 2
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 25
    below: 40
  action:
    - service: fan.xiaomi_miio_set_favorite_level
      entity_id: fan.air_purifier_pro
      data_template:
        level: 2

- alias: Oczyszczacz powietrza - poziom 3
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 40
    below: 50
  action:
    - service: fan.xiaomi_miio_set_favorite_level
      entity_id: fan.air_purifier_pro
      data_template:
        level: 3

- alias: Oczyszczacz powietrza - poziom 4
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 50
    below: 60
  action:
    - service: fan.xiaomi_miio_set_favorite_level
      entity_id: fan.air_purifier_pro
      data_template:
        level: 4

- alias: Oczyszczacz powietrza - poziom 5
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 60
    below: 70
  action:
    - service: fan.xiaomi_miio_set_favorite_level
      entity_id: fan.air_purifier_pro
      data_template:
        level: 5

- alias: Oczyszczacz powietrza - poziom 5
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 70
    below: 80
  action:
    - service: fan.xiaomi_miio_set_favorite_level
      entity_id: fan.air_purifier_pro
      data_template:
        level: 6

- alias: Oczyszczacz powietrza - poziom 6
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 80
    below: 90
  action:
    - service: fan.xiaomi_miio_set_favorite_level
      entity_id: fan.air_purifier_pro
      data_template:
        level: 7

- alias: Oczyszczacz powietrza - poziom 7
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 90
    below: 100
  action:
    - service: fan.xiaomi_miio_set_favorite_level
      entity_id: fan.air_purifier_pro
      data_template:
        level: 8

- alias: Oczyszczacz powietrza - poziom 8
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.aqi }}"
    above: 100
  action:
    - service: fan.xiaomi_miio_set_favorite_level
      entity_id: fan.air_purifier_pro
      data_template:
        level: 16