- alias: Nawilżacz powietrza - wyłącz
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: 
      - fan.air_humidifier
    value_template: "{{ state.attributes.humidity }}"
    above: 60
    for:
      minutes: 3
  action:
    - service: fan.turn_off
      entity_id: fan.air_humidifier

- alias: Nawilżacz powietrza - włącz
  trigger:
    platform: numeric_state
    entity_id: fan.air_humidifier
    value_template: "{{ state.attributes.humidity }}"
    below: 60
    for:
      minutes: 3
  action:
    - service: fan.turn_on
      entity_id: fan.air_humidifier

- alias: Nawilżacz powietrza - poziom 1
  trigger:
    platform: numeric_state
    entity_id: fan.air_humidifier
    value_template: "{{ state.attributes.humidity }}"
    above: 50
    below: 60
  action:
    - service: fan.set_speed
      entity_id: fan.air_humidifier
      data_template:
        speed: silent

- alias: Nawilżacz powietrza - poziom 2
  trigger:
    platform: numeric_state
    entity_id: fan.air_humidifier
    value_template: "{{ state.attributes.humidity }}"
    above: 40
    below: 50
  action:
    - service: fan.set_speed
      entity_id: fan.air_humidifier
      data_template:
        speed: medium

- alias: Nawilżacz powietrza - poziom 3
  trigger:
    platform: numeric_state
    entity_id: fan.air_humidifier
    value_template: "{{ state.attributes.humidity }}"
    below: 40
  action:
    - service: fan.set_speed
      entity_id: fan.air_humidifier
      data_template:
        speed: high