- alias: Nawilżacz powietrza - wyłącz
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: 
      - fan.air_purifier_pro
    value_template: "{{ state.attributes.humidity }}"
    above: 60
    for:
      minutes: 3
  action:
    - service: fan.turn_off
      entity_id: fan.air_humidifier

- alias: Nawilżacz powietrza - wyłącz na noc
  initial_state: true
  trigger:
    platform: time
    at: "00:00:00"
  action:
    - service: fan.turn_off
      entity_id: fan.air_humidifier

- alias: Nawilżacz powietrza - włącz
  trigger:
    platform: numeric_state
    entity_id: fan.air_purifier_pro
    value_template: "{{ state.attributes.humidity }}"
    below: 60
    for:
      minutes: 3
  condition:
    condition: time
    after: '07:00:00'
    before: '23:59:00'
  action:
    - service: fan.turn_on
      entity_id: fan.air_humidifier
    - delay: 
        seconds: 3
    - service: fan.set_speed
      entity_id: fan.air_humidifier
      data_template:
        speed: >
              {% if states.fan.air_purifier_pro.attributes.humidity | int < 40 %}
                high
              {% elif states.fan.air_purifier_pro.attributes.humidity | int < 50 %}
                medium
              {% else %}
                silent
              {% endif %}
