- platform: rest
  name: Airly
  resource: https://airapi.airly.eu/v2/measurements/point?lat=50.29076&lng=18.91781
  headers:
    apikey: !secret airly_api_key
  value_template: "{{ value_json['current']['values'][0]['value'] }} {{ value_json['current']['values'][1]['value'] }} {{ value_json['current']['values'][2]['value'] }} {{ value_json['current']['indexes'][0]['value'] }} {{ value_json['current']['standards'][0]['percent'] }} {{ value_json['current']['standards'][1]['percent'] }}"
  scan_interval: 300 # 5mins
- platform: template
  sensors:
    airly_pm1:
      unit_of_measurement: "μg/m3"
      value_template: "{{ states.sensor.airly.state.split(' ')[0] | round(2) }}"
    airly_pm25:
      unit_of_measurement: "μg/m3"
      value_template: "{{ states.sensor.airly.state.split(' ')[1] | round(2) }}"
    airly_pm10:
      unit_of_measurement: "μg/m3"
      value_template: "{{ states.sensor.airly.state.split(' ')[2] | round(2) }}"
    airly_aqi:
      unit_of_measurement: "units"
      value_template: "{{ states.sensor.airly.state.split(' ')[3] | round(2) }}"
    airly_pm25_percent:
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.airly.state.split(' ')[4] | round(2) }}"
    airly_pm10_percent:
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.airly.state.split(' ')[5] | round(2) }}"