- platform: rest
  name: Airly
  resource: https://airapi.airly.eu/v1/nearestSensor/measurements?latitude=50.29076&longitude=18.91781&maxDistance=1000
  headers:
    apikey: !secret airly_api_key
  value_template: "{{ value_json['airQualityIndex'] }} {{ value_json['pm25'] }} {{ value_json['pm10'] }}"
  scan_interval: 300 # 5mins
- platform: template
  sensors:
    airly_aqi:
      unit_of_measurement: "units"
      value_template: "{{ states.sensor.airly.state.split(' ')[0] | round(0) }}"
    airly_pm25:
      unit_of_measurement: "μg/m3"
      value_template: "{{ states.sensor.airly.state.split(' ')[1] | round(0) }}"
    airly_pm10:
      unit_of_measurement: "μg/m3"
      value_template: "{{ states.sensor.airly.state.split(' ')[2] | round(0) }}"
    airly_pm25_percent:
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.airly.state.split(' ')[1] | multiply(100) | multiply(0.04) | round(0) }}"