- platform: mqtt
  state_topic: "/ESP_Przedpokoj/Temp/Temperature"
  name: "Temperatura przedpokój"
  unit_of_measurement: "°C"
  value_template: '{{ value }}'

- platform: mqtt
  state_topic: "/ESP_Przedpokoj/Temp/Humidity"
  name: "Wilgotność przedpokój"
  unit_of_measurement: "%"
  value_template: '{{ value }}'