- platform: openweathermap
  api_key: !secret openweathermap_api_key
  language: pl
  forecast: true
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - humidity
    - pressure
    - clouds