- alias: Scena wyjście z domu
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.wyjscie_z_domu_i_wylaczenie_wszystkiego
      domain: scene
      service: turn_on
  action:
    - service: light.turn_on
      entity_id: light.lampka_zewnetrzna
    - service: switch.turn_on
      entity_id: switch.sonoff_1000541365
    - service: media_player.turn_off
      entity_id: media_player.sony_bravia
    - delay:
        seconds: 120
    - service: light.turn_off
      entity_id: light.lampka_zewnetrzna
    - service: switch.turn_off
      entity_id: switch.sonoff_1000541365
    
    