- alias: Scena oglądanie tv
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.ogladanie_tv
      domain: scene
      service: turn_on
  action:
    - service: mqtt.publish
      data_template:
        topic: "home/stairs/minlevel/set"
        payload_template: "{ level: \"5\" }"
    - service: light.turn_on
      entity_id: light.grzybek
      data_template:
        rgb_color: ['{{ (range(0, 255)|random) }}','{{ (range(0, 255)|random) }}','{{ (range(0, 255)|random) }}']
        brightness: 80