- alias: Scena dobranoc
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.dobranoc
      domain: scene
      service: turn_on
  action:
    - service: light.turn_on
      entity_id: light.halogen_2
    - service: light.turn_on
      entity_id: light.halogen_3
    - service: light.turn_off
      entity_id: light.lampka_zewnetrzna
    - service: media_player.turn_off
      entity_id: media_player.denon
    - service: media_player.turn_off
      entity_id: media_player.sony_bravia
    - service: light.turn_off
      entity_id: light.grzybek
    - service: light.turn_off
      entity_id: light.salon_led
    - service: mqtt.publish
      data_template:
        topic: "home/stairs/minlevel/set"
        payload_template: "{ level: \"0\" }"
    - delay: 
        seconds: 30
    - service: light.turn_off
      entity_id: light.halogen_1
    - service: light.turn_off
      entity_id: light.halogen_2
    - service: light.turn_off
      entity_id: light.halogen_3
    - service: light.turn_off
      entity_id: light.halogen_4 
    - service: switch.turn_off
      entity_id: switch.sonoff_100051420f
    - service: switch.turn_off
      entity_id: switch.sonoff_1000513cd0
    - service: switch.turn_off
      entity_id: switch.sonoff_1000511f63
    