- alias: Scena oglądanie tv
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.ogladanie_tv
      domain: scene
      service: turn_on
  action:
    - service: mqtt.publish
      data_template:
        topic: "home/stairs/minlevel/set"
        payload_template: "{ level: \"5\" }"