homeassistant:
  # Name of the location where Home Assistant is running
  name: Dom
  # Location required to calculate the time the sun rises and sets
  latitude: 50.308210
  longitude: 18.916434
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 287
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml

logger:
  default: error

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: 192.168.1.115:8123
  trusted_networks:
    - 192.168.1.0/24
  # Secrets are defined in the file secrets.yaml
  # 
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the develapi_password: !secret http_passwordopers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

mqtt:
  broker: mosquitto

group: !include groups.yaml
automation: !include_dir_merge_list custom/automations/
script: !include scripts.yaml 
scene: !include_dir_list custom/scenes/
sensor: !include_dir_merge_list custom/sensors/

influxdb:
  host: influxdb
  include:
    entities:
      - sensor.airly_pm25_percent
      - sensor.airly_pm25
      - sensor.airly_pm10
      - media_player.sony_bravia
      - media_player.denon_avrx1400h
      - light.salon_led
      - light.grzybek
      - light.halogen_1
      - light.halogen_2
      - light.halogen_3
      - light.halogen_4
      - light.lampka_zewnetrzna
      - cover.roleta_salon
      - binary_sensor.schody_wejscie_na_gore
      - binary_sensor.schody_zejscie_na_do
      - input_number.stairs_min_brightness
      - input_number.stairs_max_brightness
      - switch.sonoff_100051420f
      - switch.sonoff_1000513cd0
      - sensor.temperatura_przedpokoj
      - sensor.wilgotnosc_przedpokoj
      - media_player.spotify
      - weather.openweathermap

binary_sensor:
  - platform: workday
    country: PL
  - platform: mqtt
    command_topic: "inrelevant"
    state_topic: "home/stairs/bottom_motion_detector/set"
    name: Schody czujnik dolny
  - platform: mqtt
    command_topic: "inrelevant"
    state_topic: "home/stairs/upper_motion_detector/set"
    name: Schody czujnik górny
  - platform: mqtt
    command_topic: "inrelevant"
    state_topic: "home/stairs/set_going_down"
    name: Schody zejście na dół
  - platform: mqtt
    command_topic: "inrelevant"
    state_topic: "home/stairs/set_going_up"
    name: Schody wejście na górę

sonoff:
  username: !secret sonoff_login
  password: !secret sonoff_pass

cover:
  - platform: command_line
    covers:
      roleta_salon:
        friendly_name: Roleta salon
        command_open: "/usr/bin/curl -X GET http://192.168.1.198/changelevel?level=0"
        command_close: "/usr/bin/curl -X GET http://192.168.1.198/changelevel?level=100"
        command_stop: "/usr/bin/curl -X GET http://192.168.1.198/changelevel?level=0"
        # command_state: state_command garage
        
light:
  - platform: limitlessled
    bridges:
    - host: 192.168.1.101
      groups:
      - number: 1
        type: rgbww
        name: Salon LED
        fade: off
      - number: 2
        type: bridge-led
        name: Grzybek
        fade: off
  - platform: mqtt
    name: "Halogen 1"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay1/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/16"
    payload_on: "0"
    payload_off: "1"
  - platform: mqtt
    name: "Halogen 2"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay2/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/2"
    payload_on: "0"
    payload_off: "1"
  - platform: mqtt
    name: "Halogen 3"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay3/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/13"
    payload_on: "0"
    payload_off: "1"
  - platform: mqtt
    name: "Halogen 4"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay4/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/12"
    payload_on: "0"
    payload_off: "1"
  - platform: mqtt
    name: "Lampka zewnętrzna"
    state_topic: "/ESP_Przedpokoj/Relay1/Switch"
    command_topic: "/ESP_Przedpokoj/gpio/12"
    payload_on: "0"
    payload_off: "1"


media_player:
  - platform: braviatv
    name: "Sony Bravia"
    host: 192.168.1.108
  - platform: spotify
    client_id: !secret spotify_clientid
    client_secret: !secret spotify_clientsecret
  - platform: denon
    host: 192.168.1.100

#input_select:
#  rozrywka:
#    name: Rozrywka
#    options:
#      - TV
#      - PS4
#      - Kodi
#    initial: TV
#    icon: mdi:remote

input_number:
  volume_setpoint:
    name: Denon głośność
    initial: 25
    min: 1
    max: 100
    step: 1
  stairs_min_brightness:
    name: Minimalna jasność schodów
    initial: 0
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  stairs_max_brightness:
    name: Maksymalna jasność schodów
    initial: 100
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'

input_boolean:
  set_roller_10:
    name: Roleta 10%
    initial: off
  set_roller_20:
    name: Roleta 20%
    initial: off
  set_roller_30:
    name: Roleta 30%
    initial: off
  set_roller_50:
    name: Roleta 50%
    initial: off
  set_roller_70:
    name: Roleta 70%
    initial: off

rest_command:
  window_cover_percent:
    url: 'http://192.168.1.198/changelevel?level={{percent}}'
  stairs_min_brightness:
    url: 'http://192.168.1.196/changesettings?minlevel={{minlevel}}'
  stairs_max_brightness:
    url: 'http://192.168.1.196/changesettings?maxlevel={{maxlevel}}'

notify:
  - platform: pushbullet
    name: push
    api_key: !secret pushbullet_api_key

device_tracker:
- platform: nmap_tracker
  hosts:
    - 192.168.1.103-104
  track_new_devices: yes
  interval_seconds: 10
  home_interval: 1

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
