homeassistant:
  # Name of the location where Home Assistant is running
  name: Dom
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 287
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml

logger:
  default: warning
  logs:
    homeassistant.core: critical
    homeassistant.components.fan: error
    homeassistant.config_entries: error

# Enables the frontend
frontend:

# Enables configuration UI
config:

api:

mobile_app:

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 127.0.0.1

# http:
#   base_url: !secret base_url
#   ssl_certificate: /etc/letsencrypt/live/arekha.duckdns.org/fullchain.pem
#   ssl_key: /etc/letsencrypt/live/arekha.duckdns.org/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the develapi_password: !secret http_passwordopers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
# Optional, allows Home Assistant developers to focus on popular components.
# include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

system_health:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: "pl"

# Cloud
#cloud:

google_assistant:
  project_id: home-assistant-267be
  service_account: !include google-assistant.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - cover
    - media_player
    - scene
    - script
  entity_config:
    scene.dobranoc:
      name: "Goodnight"
      aliases:
        - Goodnight
        - "See you"
        - "Bye"
        - "Bye bye"
    scene.ogladanie_tv:
      name: "Watch TV"
    scene.bieganie:
      name: "Running"
    scene.zakoncz_bieganie:
      name: "Running Stop"
      aliases:
        - "Running stop"
        - "Stop running"
        - "Rest"
    scene.standardowe_oswietlenie:
      name: "Standard light"
    scene.wyjscie_z_domu:
      name: "Out home"
      aliases:
        - "Out home"
    scene.swiatlo_zewnetrzne:
      name: "External and garden light"
      aliases:
        - "External and garden light"
    scene.paulina_idzie_spac:
      name: "Paulina goes to sleep"
      aliases:
        - "Paulina goes to sleep"

mqtt:
  light:  
  - name: "Halogen 1"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay1/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/16"
    payload_on: "0"
    payload_off: "1"
  - name: "Halogen 2"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay2/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/2"
    payload_on: "0"
    payload_off: "1"
  - name: "Halogen 3"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay3/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/13"
    payload_on: "0"
    payload_off: "1"
  - name: "Halogen 4"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay4/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/12"
    payload_on: "0"
    payload_off: "1"
  - name: "Lampka zewnętrzna"
    state_topic: "/ESP_Przedpokoj/Relay1/Switch"
    command_topic: "/ESP_Przedpokoj/gpio/12"
    payload_on: "0"
    payload_off: "1"
  binary_sensor:
  - state_topic: "home/stairs/bottom_motion_detector/set"
    name: Schody czujnik dolny
  - state_topic: "home/stairs/upper_motion_detector/set"
    name: Schody czujnik górny
  - state_topic: "home/stairs/set_going_down"
    name: Schody zejście na dół
  - state_topic: "home/stairs/set_going_up"
    name: Schody wejście na górę
  cover:
  - name: "Roleta salon"
    state_topic: "shellies/shellyswitch25-98CDAC24CF74/roller/0"
    command_topic: "shellies/shellyswitch25-98CDAC24CF74/roller/0/command"
    position_topic: "shellies/shellyswitch25-98CDAC24CF74/roller/0/pos"
    set_position_topic: "shellies/shellyswitch25-98CDAC24CF74/roller/0/command/pos"
    # availability_topic: "shellies/shellyswitch25-98CDAC24CF74/online"
    payload_available: "true"
    payload_not_available: "false"
    qos: 1
    retain: false
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    position_open: 100
    position_closed: 0
    optimistic: false
  sensor:
  - state_topic: "/ESP_Przedpokoj/Temp/Temperature"
    name: "Temperatura przedpokój"
    unit_of_measurement: "°C"
    value_template: '{{ value }}'
  - state_topic: "/ESP_Przedpokoj/Temp/Humidity"
    name: "Wilgotność przedpokój"
    unit_of_measurement: "%"
    value_template: '{{ value }}'

automation: !include_dir_merge_list custom/automations/
script: !include_dir_merge_named custom/scripts/

scene: !include_dir_list custom/scenes/
sensor: !include_dir_merge_list custom/sensors/

recorder:
  db_url: mysql://root:wsadqe@192.168.1.115:3306/home_assistant?charset=utf8
  include:
    entities:
      - media_player.sony_bravia_tv
      - media_player.denon
      - light.salon_led
      - light.grzybek
      - light.halogen_1
      - light.halogen_2
      - light.halogen_3
      - light.halogen_4
      - light.lampka_zewnetrzna
      - cover.roleta_salon
      - binary_sensor.schody_wejscie_na_gore
      - binary_sensor.schody_zejscie_na_do
      - switch.sonoff_100051420f
      - switch.sonoff_1000513cd0
      - switch.sonoff_1000511f63
      - media_player.spotify_arkadiusz_neuman
      - vacuum.roborock_s5
      - media_player.playstation_4
      - !secret steam_sensor_name
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping

influxdb:
  host: localhost
  username: admin
  password: password123
  include:
    entities:
      - media_player.sony_bravia_tv
      - media_player.denon
      - light.salon_led
      - light.grzybek
      - light.halogen_1
      - light.halogen_2
      - light.halogen_3
      - light.halogen_4
      - light.lampka_zewnetrzna
      - cover.roleta_salon
      - binary_sensor.schody_wejscie_na_gore
      - binary_sensor.schody_zejscie_na_do
      - input_number.stairs_min_brightness
      - input_number.stairs_max_brightness
      - switch.sonoff_100051420f
      - switch.sonoff_1000513cd0
      - switch.sonoff_1000511f63
      - sensor.temperatura_przedpokoj
      - sensor.wilgotnosc_przedpokoj
      - media_player.spotify_arkadiusz_neuman
      - weather.openweathermap
      - vacuum.roborock_s5
      - media_player.playstation_4
      - !secret steam_sensor_name
      - fan.filtr_powietrza
      - fan.air_humidifier
      - fan.mi_air_purifier_2s
      - sensor.sunlight_pct
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping

binary_sensor:
  - platform: workday
    country: PL
  - platform: ping #need to add ip of HA to firewall rule
    host: 192.168.1.106
    name: "Laptop Ethernet"
    count: 2
    scan_interval: 2
  - platform: ping
    host: 192.168.1.125
    name: "Laptop WiFi"
    count: 2
  - platform: ping #need to add ip of HA to firewall rule
    host: 192.168.1.135
    name: "Laptop Służbowy WiFi"
    count: 2
    scan_interval: 2
  - platform: ping #need to add ip of HA to firewall rule
    host: 192.168.1.140
    name: "Komputer stacjonarny"
    count: 2
    scan_interval: 2

sonoff:
  username: !secret sonoff_login
  password: !secret sonoff_pass

light:
  - platform: limitlessled
    bridges:
      - host: 192.168.1.101
        groups:
          - number: 1
            type: rgbww
            name: Salon LED
            fade: off
          - number: 2
            type: bridge-led
            name: Grzybek
            fade: off

input_number:
  denon_volume:
    name: Denon głośność
    initial: 25
    min: 1
    max: 100
    step: 1
  stairs_min_brightness:
    name: Minimalna jasność schodów
    initial: 0
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
  stairs_max_brightness:
    name: Maksymalna jasność schodów
    initial: 100
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
  minimum_light_for_light:
    name: Minimalne światło
    initial: 1000
    min: 0
    max: 2000
    step: 100
    unit_of_measurement: "lux"

input_boolean:
  auto_office_light:
    name: Automatycznie steruj oświetleniem w salonie
    initial: true
  holiday_mode:
    name: Tryb wakacyjny
    initial: false

notify:
  - platform: pushbullet
    name: push
    api_key: !secret pushbullet_api_key

input_select:
  air_purifier_2s_automation_type:
    name: Typ automatyzacji
    options:
      - Sypialnia
      - Trening na bieżni
    icon: mdi:format-list-bulleted-type
