homeassistant:
  # Name of the location where Home Assistant is running
  name: Dom
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 287
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml

logger:
  default: info
  logs:
    homeassistant.core: critical

# Enables the frontend
frontend:

# Enables configuration UI
config:

api:

http:
  base_url: !secret base_url
  ssl_certificate: /etc/letsencrypt/live/arekha.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/arekha.duckdns.org/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the develapi_password: !secret http_passwordopers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

system_health:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'pl'

# Cloud
#cloud:

google_assistant:
  project_id: tidy-elf-231815
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - group
    - cover
    - media_player
    - scene
    - script

mqtt:
  broker: localhost

hacs:
  token: !secret hacs_github_token

group: !include groups.yaml
automation: !include_dir_merge_list custom/automations/
script: !include_dir_merge_named custom/scripts/

scene: !include_dir_list custom/scenes/
sensor: !include_dir_merge_list custom/sensors/

recorder:
  db_url: mysql://root:wsadqe@192.168.1.115:3306/home_assistant?charset=utf8
  purge_interval: 0
  include:
    entities:
      - media_player.sony_bravia
      - media_player.denon
      - light.salon_led
      - light.grzybek
      - light.halogen_1
      - light.halogen_2
      - light.halogen_3
      - light.halogen_4
      - light.lampka_zewnetrzna
      - cover.roleta_salon
      - binary_sensor.schody_wejscie_na_gore
      - binary_sensor.schody_zejscie_na_do
      - switch.sonoff_100051420f
      - switch.sonoff_1000513cd0
      - switch.sonoff_1000511f63
      - media_player.spotify
      - vacuum.roborock
      - media_player.playstation_4
      - !secret steam_sensor_name
    

influxdb:
  host: localhost
  include:
    entities:
      - sensor.airly_pm1
      - sensor.airly_pm25_percent
      - sensor.airly_pm10_percent
      - sensor.airly_pm25
      - sensor.airly_pm10
      - media_player.sony_bravia
      - media_player.denon
      - light.salon_led
      - light.grzybek
      - light.halogen_1
      - light.halogen_2
      - light.halogen_3
      - light.halogen_4
      - light.lampka_zewnetrzna
      - cover.roleta_salon
      - binary_sensor.schody_wejscie_na_gore
      - binary_sensor.schody_zejscie_na_do
      - input_number.stairs_min_brightness
      - input_number.stairs_max_brightness
      - switch.sonoff_100051420f
      - switch.sonoff_1000513cd0
      - switch.sonoff_1000511f63
      - sensor.temperatura_przedpokoj
      - sensor.wilgotnosc_przedpokoj
      - media_player.spotify
      - weather.openweathermap
      - vacuum.roborock
      - media_player.playstation_4
      - !secret steam_sensor_name
      - fan.air_purifier_pro
      - fan.air_humidifier
      - fan.air_purifier_2s

binary_sensor:
  - platform: workday
    country: PL
  - platform: mqtt
    state_topic: "home/stairs/bottom_motion_detector/set"
    name: Schody czujnik dolny
  - platform: mqtt
    state_topic: "home/stairs/upper_motion_detector/set"
    name: Schody czujnik górny
  - platform: mqtt
    state_topic: "home/stairs/set_going_down"
    name: Schody zejście na dół
  - platform: mqtt
    state_topic: "home/stairs/set_going_up"
    name: Schody wejście na górę

sonoff:
  username: !secret sonoff_login
  password: !secret sonoff_pass

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.113
    token: !secret roborock
    name: Roborock

fan:
  - platform: xiaomi_miio
    host: 192.168.1.121
    token: !secret air_purifier_pro
    name: "Air Purifier Pro"
  - platform: xiaomi_miio
    host: 192.168.1.119
    token: !secret air_purifier_2s
    name: "Air Purifier 2s"
  - platform: xiaomi_miio
    host: 192.168.1.112
    token: !secret air_humidifier
    name: "Air Humidifier"

cover:
  - platform: mqtt
    name: "Roleta salon"
    command_topic: "home/cover/set"
    position_topic: "home/cover/position"
    set_position_topic: "home/cover/set_position"
    payload_open: "{ state: \"open\" }"
    payload_close: "{ state: \"close\" }"
    payload_stop: "{ state: \"stop\" }"
    retain: false
    optimistic: false
        
light:
  - platform: limitlessled
    bridges:
    - host: 192.168.1.101
      groups:
      - number: 1
        type: rgbww
        name: Salon LED
        fade: off
      - number: 2
        type: bridge-led
        name: Grzybek
        fade: off
  - platform: mqtt
    name: "Halogen 1"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay1/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/16"
    payload_on: "0"
    payload_off: "1"
  - platform: mqtt
    name: "Halogen 2"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay2/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/2"
    payload_on: "0"
    payload_off: "1"
  - platform: mqtt
    name: "Halogen 3"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay3/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/13"
    payload_on: "0"
    payload_off: "1"
  - platform: mqtt
    name: "Halogen 4"
    state_topic: "/ESP_Lampy_Salon_Boczne/Relay4/Switch"
    command_topic: "/ESP_Lampy_Salon_Boczne/gpio/12"
    payload_on: "0"
    payload_off: "1"
  - platform: mqtt
    name: "Lampka zewnętrzna"
    state_topic: "/ESP_Przedpokoj/Relay1/Switch"
    command_topic: "/ESP_Przedpokoj/gpio/12"
    payload_on: "0"
    payload_off: "1"


media_player:
  - platform: braviatv
    name: "Sony Bravia"
    host: 192.168.1.108
  - platform: spotify
    client_id: !secret spotify_clientid
    client_secret: !secret spotify_clientsecret
  - platform: denon
    host: 192.168.1.100

cast:
  media_player:
    - host: 192.168.1.108

input_number:
  denon_volume:
    name: Denon głośność
    initial: 25
    min: 1
    max: 100
    step: 1
  stairs_min_brightness:
    name: Minimalna jasność schodów
    initial: 0
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
  stairs_max_brightness:
    name: Maksymalna jasność schodów
    initial: 100
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'

input_boolean:
  notify_weather:
    name: Informuj o pogodzie po zejściu
    initial: off

notify:
  - platform: pushbullet
    name: push
    api_key: !secret pushbullet_api_key

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    mode: daily

input_select:
  air_purifier_2s_automation_type:
    name: Typ automatyzacji
    options:
      - Sypialnia
      - Trening na bieżni
    icon: mdi:format-list-bulleted-type