- alias: Oświecenie świateł podczas przyjścia do domu po zmierzchu
  trigger:
    platform: state
    entity_id: 
      - device_tracker.2047dafb928a
      - device_tracker.f4f5dbc1deb7
    from: 'not_home'
    to: 'home'
  action:
    - service: notify.push
      data:
        message: "Ktoś przyszedł do domu"
    - service: light.turn_on
      entity_id: light.halogen_2
    - service: light.turn_on
      entity_id: light.halogen_3
    - service: switch.turn_on
      entity_id: switch.external_door_light
    - delay: 
        minutes: 10
    - service: switch.turn_off
      entity_id: switch.external_door_light
    - service: light.turn_off
      entity_id: light.halogen_2
    - service: light.turn_off
      entity_id: light.halogen_3
  condition:
    - condition: sun
      after: sunset
      after_offset: "-0:30:00"