- alias: Scena standardowe oświetlenie
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.standardowe_oswietlenie
      domain: scene
      service: turn_on
  action:
    - service: rest_command.stairs_min_brightness
      data_template:
        minlevel: 20