- alias: "Zejście po schodach rano Pati"
  trigger:
    platform: state
    entity_id: binary_sensor.schody_zejscie_na_do
    to: 'on'
  condition:
    - condition: time
      after: '04:30:00'
      before: '06:00:00'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.halogen_2
    - service: light.turn_on
      entity_id: light.halogen_3
    - service: switch.turn_on
      entity_id: switch.sonoff_100051420f
    - service: switch.turn_on
      entity_id: switch.sonoff_1000513cd0
    - delay: 
        minutes: 20
    - service: switch.turn_on
      entity_id: switch.external_door_light
    - delay: 
        minutes: 20
    - service: switch.turn_off
      entity_id: switch.external_door_light
    - service: light.turn_off
      entity_id: light.halogen_2
    - service: light.turn_off
      entity_id: light.halogen_3
    - service: switch.turn_off
      entity_id: switch.sonoff_100051420f
    - service: switch.turn_off
      entity_id: switch.sonoff_1000513cd0

- alias: "Zejście po schodach rano Arek"
  trigger:
    platform: state
    entity_id: binary_sensor.schody_zejscie_na_do
    to: 'on'
  condition:
    - condition: time
      after: '07:00:00'
      before: '09:00:00'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.halogen_2
    - service: light.turn_on
      entity_id: light.halogen_3
    - service: rest_command.window_cover_percent
      data:
        percent: 0
    - delay: #na wszelki wypadek, gdyby górny sensor nie zadziałał
        minutes: 20
    - service: light.turn_off
      entity_id: light.halogen_2
    - service: light.turn_off
      entity_id: light.halogen_3

- alias: "Wejście po schodach rano Arek"
  trigger:
    platform: state
    entity_id: binary_sensor.schody_wejscie_na_gore
    to: 'on'
  condition:
    - condition: time
      after: '07:00:00'
      before: '09:30:00'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.halogen_2
    - service: light.turn_off
      entity_id: light.halogen_3

- alias: "Zejście po schodach weekend"
  trigger:
    platform: state
    entity_id: binary_sensor.schody_zejscie_na_do
    to: 'on'
  condition:
    - condition: time
      after: '04:30:00'
      before: '12:00:00'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
  action:
    - service: rest_command.window_cover_percent
      data:
        percent: 0
    

- alias: "Choinka - zejście po schodach rano Arek"
  trigger:
    platform: state
    entity_id: binary_sensor.schody_zejscie_na_do
    to: 'on'
  condition:
    - condition: time
      after: '07:00:00'
      before: '14:30:00'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_100051420f
    - service: switch.turn_on
      entity_id: switch.sonoff_1000513cd0

- alias: "Choinka - wejście po schodach rano Arek"
  trigger:
    platform: state
    entity_id: binary_sensor.schody_wejscie_na_gore
    to: 'on'
  condition:
    - condition: time
      after: '07:00:00'
      before: '15:00:00'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_100051420f
    - service: switch.turn_off
      entity_id: switch.sonoff_1000513cd0