- alias: "Zejście po schodach weekend"
  trigger:
    platform: state
    entity_id: binary_sensor.schody_zejscie_na_do
    to: 'on'
  condition:
    - condition: sun
      after: sunrise
      after_offset: "00:00:00"
    - condition: time
      before: '12:00:00'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
  action:
    - service: rest_command.window_cover_percent
      data:
        percent: 0