- alias: "Zejście po schodach rano Pati"
  trigger:
    platform: state
    entity_id: binary_sensor.schody_zejscie_na_do
    to: 'on'
  condition:
    - condition: time
      after: '04:30:00'
      before: '06:00:00'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    # - service: light.turn_on
    #   entity_id: light.halogen_2
    # - service: light.turn_on
    #   entity_id: light.halogen_3
    - service: switch.turn_on
      entity_id: switch.sonoff_100051420f
    - service: switch.turn_on
      entity_id: switch.sonoff_1000513cd0
    - delay: 
        minutes: 20
    - service: light.turn_on
      entity_id: light.lampka_zewnetrzna
    - delay: 
        minutes: 15
    - service: light.turn_off
      entity_id: light.lampka_zewnetrzna
    # - service: light.turn_off
    #   entity_id: light.halogen_2
    # - service: light.turn_off
    #   entity_id: light.halogen_3
    - service: switch.turn_off
      entity_id: switch.sonoff_100051420f
    - service: switch.turn_off
      entity_id: switch.sonoff_1000513cd0